### ISSUE TITLE
trouble with xml input

### ISSUE THREAD

**Issue by gymel** [lex-lingo/lingo#15]
lingo v1.8.7
nokogiri v1.6.7.2 with libxml 2.9.3 under ruby 2.2.4p230 (Cygwin)
nokogiri v1.6.3.1 with libxml 2.9.1 under ruby 2.1.5p273 (Debian)

After adding  filter: 'xml' to the text_reader segment of lingo.cfg in the demo setup, the call

lingo text.xml

bails out with a type error

progress/usr/lib/ruby/vendor_ruby/nokogiri/xml/document.rb:52:in `read_io': no implicit conversion of Encoding into String (TypeError)
        from /usr/lib/ruby/vendor_ruby/nokogiri/xml/document.rb:52:in `parse'
        from /usr/lib/ruby/vendor_ruby/nokogiri/xml.rb:33:in `XML'
        from /var/lib/gems/2.1.0/gems/lingo-1.8.7/lib/lingo/attendee/text_reader.rb:193:in `filter_html'

This might be a bug in nokogiri (read_io is a C subroutine and doesn't seem to possess the full casting magic of ruby) but anyway, changing the parameter @encode to @encode.name in the application of Nokogiri.send in the filter_html definition of attendee/text_reader..rb remedies this.

HOWEVER after this fix I get
progress/var/lib/gems/2.1.0/gems/lingo-1.8.7/lib/lingo/attendee/text_reader.rb:144:in `block (3 levels) in control': undefined method `bytesize' for nil:NilClass (NoMethodError)

This seems to be related to a clash further up in text_reader.rb, within the @files.each loop in def control io is assigned a File object by open_path but subsequently within the &block associated with Progress.new reassigned with the Enumerator object returned by the filter() call.

I'm not sure what is intended here, disambiguating the names yielded for the following .each loop just _one_ iteration where line (variable) containing the text content of the whole xml document with many embedded \n, but lingo processed only the last line (wrt the \n) of this.

**Comment by blackwinter** [comment]
Hi Thomas,

thanks for your report! I pushed a [prerelease gem](https://rubygems.org/gems/lingo/versions/1.8.8.pre1) that addresses the following issues:

0. `no implicit conversion of Encoding into String`: Changed `@encoding` to `@encoding.to_s` in `Lingo::Attendee::TextReader#filter_html`.
0. "xml document with many embedded \n, but lingo processed only the last line (wrt the \n) of this": Changed `x.text` to `x.text.each_line` in `Lingo::Attendee::TextReader#text_enum`.

Could you give it a try and report back? (`gem install lingo --pre` and then `lingo _1.8.8.pre1_ ...`)

I could not reproduce a case where `line` would be `nil` in `Lingo::Attendee::TextReader#control` (`undefined method 'bytesize' for nil:NilClass`). Could you maybe provide an XML file that causes this error?

**Comment by gymel** [comment]
Great, with your fixes my test XML file got processed like a charm.

As for the open issue: It's not a nil "line" which triggered the original error, but "io" at close() time is not what it used to be at open() time. You masked the error by introducing an "if io.respnd_to?(:close)" in 1.8.8.pre1, but I suggest that you have a closer look again at the line

    pos = 0 unless pos?(io = filter(io, path, progress))

connected to the Progress.new() call between io.open and io.close: It seems that not all filter_something methods return something comparable to io, or - to stick with the facts I tested - at least text_enum(Nokogiri.send()...) is a completely different animal from the original "io" (a file). But maybe Nokogiri already closed the io object it had been processing and the whole question doesn't matter altogether...

**Comment by blackwinter** [comment]
Ok, I'll release version 1.8.8 (or maybe 1.9.0) soon.

> As for the open issue: It's not a nil "line" which triggered the original error, but "io" at close() time is not what it used to be at open() time.

The error `undefined method 'bytesize' for nil:NilClass` can only result from `line` being `nil`.

> You masked the error by introducing an "if io.respnd_to?(:close)" in 1.8.8.pre1, but I suggest that you have a closer look again at the line

That's correct, it was a quick fix. I'm going to refactor the code for the final release. However, the fact that `io` doesn't have to be an actual `IO` object is considered a feature. We sneak a different kind of object in its place if the original input is filtered through a type-specific processor.

**Comment by gymel** [comment]
Oh, without noticing I had been getting two different error messages on two systems (both with a plain install of lingo 1.8.7 with "@encoding" as parameter to Nokogiri.send() patched as "@encoding.name"):

What I had been trying to discuss was

    /home/thomas/.gem/ruby/gems/lingo-1.8.7/lib/lingo/attendee/text_reader.rb:154:in `block in control': undefined method `close' for #<Enumerator: #<Enumerator::Generator:0x80bfc734>:each> (NoMethodError)

for the following setup

    # Nokogiri (1.6.7.2)
    ---
    warnings: []
    nokogiri: 1.6.7.2
    ruby:
      version: 2.2.4
      platform: i386-cygwin
      description: ruby 2.2.4p230 (2015-12-16 revision 53155) [i386-cygwin]
      engine: ruby
    libxml:
      binding: extension
      source: system
      compiled: 2.9.3
      loaded: 2.9.3


But on the other machine (Debian jessie) I got (and pasted here):

    /home/thomas/lingo-work/2lingo.xml: progress/var/lib/gems/2.1.0/gems/lingo-1.8.7/lib/lingo/attendee/text_reader.rb:144:in `block (3 levels) in control': undefined method `bytesize' for nil:NilClass (NoMethodError)

with the following setup:

    # Nokogiri (1.6.3.1)
    ---
    warnings: []
    nokogiri: 1.6.3.1
    ruby:
      version: 2.1.5
      platform: x86_64-linux-gnu
      description: ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]
      engine: ruby
    libxml:
      binding: extension
      source: system
      compiled: 2.9.1
      loaded: 2.9.1

My "success" report from this afternoon was with regard to 1.8.8.pre1 under the Cygwin setup. But on the Debian setup it runs successfully, too!
